# This is a basic workflow that is manually triggered

name: Publish website

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
#     inputs:
#        branch:
        # Friendly description to be shown in the UI instead of 'name'
#          description: 'Branch to deploy (default is master)'
        # Default value if no value is explicitly provided
#          default: 'master'
        # Input has to be provided for the workflow to run
#          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  FTP-Deploy-Action:
    name: FTP Deploy (master)
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 248147.w47.wedos.net
        FTP_USERNAME: w248147_github
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: web
        REMOTE_DIR: www/test
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
