name: Build & Publish website

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run Clean
        uses: borales/actions-yarn@v4
        with:
          cmd: clean

      - name: Run Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 248147.w47.wedos.net
          username: w248147_github
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
      
